#Script to create the database
CREATE TABLE `user` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `name` varchar(25) NOT NULL,
  `age` int NOT NULL,
 `isAdmin` BIT NOT NULL,
 `createdDate` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

#Requests to fill the database with test data
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Admin', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('User', 23, 0);
insert into user (name, age, isAdmin) values('Користувач', 15, 0);
insert into user (name, age, isAdmin) values('User3', 45, 0);
insert into user (name, age, isAdmin) values('User1', 45, 0);
insert into user (name, age, isAdmin) values('Адмін', 50, 1);
insert into user (name, age, isAdmin) values('User2', 45, 0);
insert into user (name, age, isAdmin) values('Іванов Іван Іванович', 37, 0);
insert into user (name, age, isAdmin) values('Petrov Petro Petrovich', 29, 0);
